version: '3.6'

services:
  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    build:
      context: image/php-fpm
    env_file:
      - ./.env
    networks:
      - default

networks:
  default:
    driver: bridge
