framework:
    cache:
        app: cache.adapter.filesystem

        pools:
            bin_data.cache:
                adapter: cache.app
            exchange_rates.cache:
                adapter: cache.app

when@test:
    framework:
        cache:
            app: cache.adapter.array
